[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino

upload_speed = 921600
monitor_speed = 115200

; TFT_eSPI picks up User_Setup.h from include/ automatically
; because the project include dir has higher priority than the library

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    bblanchon/ArduinoJson @ ^7.3.0
    https://github.com/PaulStoffregen/XPT2046_Touchscreen
